<?php


namespace app\modules\admin\controllers;


use app\models\CompleteForm;
use app\models\DeleteForm;
use app\models\Request;
use app\models\RequestAdd;
use yii\web\Controller;

class MainController extends Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->user->identity->type!=2){
            return $this->redirect('');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionRequests(){
        $request = Request::find()->orderBy('status')->all();
        return $this->render('requests',['request'=>$request]);
    }

    public function actionDelete($id){
        if ($request = Request::findOne($id)){
            if ($request->status==1){
                $model = new DeleteForm();
                if ($model->load(\Yii::$app->request->post())&&$model->validate()){
                    if ($model->doDelete($request)){
                        \Yii::$app->session->setFlash("goodDelete",'sad');
                        if (\Yii::$app->request->isPjax) {

                            $model = new CompleteForm();
                            return $this->refresh();

                        } elseif (\Yii::$app->request->isPost) {

                            $this->refresh();

                        }

                    }
                }
                return $this->render('delete',['model'=>$model]);
            }
            return $this->redirect('/admin/main/requests');
        }
        return $this->redirect('/admin/main/requests');
    }

    public function actionComplete($id){
        if ($request = Request::findOne($id)){
            if ($request->status==1){
                $model = new CompleteForm();
                if ($model->load(\Yii::$app->request->post())&&$model->validate()){
                    if ($model->goComplete($request)){
                        \Yii::$app->session->setFlash("goodComplete",'sad');
                        if (\Yii::$app->request->isPjax) {

                            $model = new CompleteForm();

                        } elseif (\Yii::$app->request->isPost) {

                            $this->refresh();

                        }
                    }
                }
                return $this->render('complete',['model'=>$model]);
            }
            return $this->redirect('/admin/main/requests');
        }
        return $this->redirect('/admin/main/requests');
    }
}