<?php


namespace app\controllers;


use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\Request;
use yii\bootstrap\ActiveForm;
use yii\web\Controller;
use yii\web\Response;

class MainController extends Controller
{

    public function beforeAction($action)
    {
        if (\Yii::$app->user->identity->type==2){
            return $this->redirect('/admin/main/requests');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionRegistration()
    {
        if (!\Yii::$app->user->isGuest){
            return $this->redirect('/');
        }

        $model = new RegistrationForm();

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

            $model->registration();

            \Yii::$app->session->setFlash("goodReg", "Вы успешно зарегистрировались.");

            if (\Yii::$app->request->isPjax) {

                $model = new RegistrationForm();

            } elseif (\Yii::$app->request->isPost) {

                $this->refresh();

            }
        }
        return $this->render('registration', ['model' => $model]);
    }

    public function actionLogin(){
        if (!\Yii::$app->user->isGuest){
            return $this->redirect('/');
        }
        $model = new LoginForm();
        if ($model->load(\Yii::$app->request->post())&&$model->validate()){
            $model->login();
            return $this->redirect('/');
        }
        return $this->render("login",['model'=>$model]);
    }

    public function actionLogout(){
        if (\Yii::$app->user->isGuest){
            return $this->redirect('/');
        }
        \Yii::$app->user->logout();
        return $this->redirect('/');

    }

    public function actionAll(){
        $request = Request::find()->where(['status'=>2])->limit(4)->all();
        return $this->render('all',['request'=>$request]);
    }
}