<?php


namespace app\controllers;


use app\models\Category;

use app\models\Request;
use app\models\RequestAdd;
use app\models\RequestSearch;
use app\models\Status;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class RequestController extends Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->user->identity->type==2){
            return $this->redirect('/admin/main/requests');
        }
        elseif(\Yii::$app->user->isGuest){
            return $this->goHome();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionAdd(){
        $model = new RequestAdd();
        $categorys = ArrayHelper::map(Category::find()->all(),'id','name');
        if ($model->load(\Yii::$app->request->post())&&$model->validate()){
            if ($model->add()){
                \Yii::$app->session->setFlash("goodAdd",'sad');
                if (\Yii::$app->request->isPjax) {

                    $model = new RequestAdd();

                } elseif (\Yii::$app->request->isPost) {

                    $this->refresh();

                }
            }
        }

        return $this->render('add',['model'=>$model,'categorys'=>$categorys]);
    }


    public function actionMy(){

        $request = Request::find()->where(['owner'=>\Yii::$app->user->getId()]);
        $statusFilter = ArrayHelper::map(Status::find()->all(),'id','name');
        $searchModel = new RequestSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('my',['dataProvider'=>$dataProvider,'request'=>$request,'statusFilter'=>$statusFilter,'searchModel'=>$searchModel]);
    }

    public function actionDelete($id){
        if ($request = Request::find()->where(['owner'=>\Yii::$app->user->getId(),'id'=>$id])->one()){
            $request->delete();
            return $this->redirect('/request/my');
        }
        return $this->redirect('/request/my');
    }
}